apiVersion: v1
kind: Service
metadata:
  name: {{ include "tproxy.fullname" . }}
  labels:
    {{- include "tproxy.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.tproxy.httpPort }}
      targetPort: {{ .Values.tproxy.httpPort }}
      protocol: TCP
      name: http
    - port: {{ .Values.tproxy.httpsPort }}
      targetPort: {{ .Values.tproxy.httpsPort }}
      protocol: TCP
      name: https
  selector:
    {{- include "tproxy.selectorLabels" . | nindent 4 }}
